CREATE TABLE IF NOT EXISTS {0} (
    Id SERIAL PRIMARY KEY,
    ChildId INTEGER NOT NULL,
    ChildFullNames TEXT NOT NULL,
    BiologicalChild BOOLEAN NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
